### ISSUE TITLE
docs: add documentation for layer examples

### ISSUE THREAD

**Issue by und3fined-v01d** [und3fined-v01d/webxr-layers#32]
## TODO

- [ ] Documentation for basic layer examples (class structure, common methods)
- [ ] Documentation for hand interractions
- [ ] Documentation for custom classes extended from three.js
- [ ] Documentation for classes that enable hand motion
- [ ] Documentation for classes that enable layer resizing

**Comment by zhixiangteoh** [comment]
WIP: https://github.com/und3fined-v01d/webxr-layers/tree/docs
